version: '3.1'
services:
  db:
    image: "postgres:10.5"
    ports:
      - "5432:5432"
    volumes:
    - ./sql/migration-001.sql:/docker-entrypoint-initdb.d/migration-001.sql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: konnektis

  app:
    build: .
    ports:
     - "3001:3001"
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/build
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      PGPASSWORD: 123456
      PGUSER: postgres
      PGDATABASE: konnektis
      PGHOST: db
    command: ["npm", "run", "backend"]

